### ISSUE TITLE
display: none; instead of visibility: hidden;

### ISSUE THREAD

**Issue by pareeohnos** [Akryum/v-tooltip#146]
I've run into an issue with v-popover due to its use of `visiblity: hidden` to hide the popover rather than using `display: none;` - the issue being it doesn't have an impact on child elements that override this property. In our application we have a tooltip that contains an accordion, and the accordion works by showing/hiding its panels using `visibility: visible !important;` (horrible yes, but another library)

Unfortunately, when the tooltip then gets hidden, the expanded accordion remains visible on the page until the tooltip is removed from the DOM.

Is there any particular reason not to use `display: none;` instead? Happy to open a PR if you'd be willing to change this

**Comment by DivaynshuClecotech** [comment]
@pareeohnos I did not make any changes to the tooltip library's css, we can use `display: none`. I don't see any problem with it.

**Comment by amoshydra** [comment]
Faced a similar situation today while trying to render a tall popover on a small screen.

I suspect the use of `visibility: hidden` used so that the fade out animation will work. 

However, (as of 2.0.0-rc.33) fade out animation play in 150ms. But the tooltip DOM is only removed after 5 seconds when using the default config: 
```yaml
disposeTimeout: 5000
```

Changing the `disposeTimeout` to ~150ms help ease your problem.

**Comment by rootman** [comment]
Visibility hidden also disables the leave transition as it will hide the popover in an instant.
Maybe just use opacity and pointer-events: none so make fade out work? Just a first idea off the top of my head, do not know about the implications yet.

**Comment by Akryum** [comment]
v-tooltip doesn't have any CSS included, customize your CSS to change it to `display: none;` if you need it.
