### ISSUE TITLE
Popover Placement not working on Firefox and Safari

### ISSUE THREAD

**Issue by virtualbjorn** [Akryum/v-tooltip#149]
The placement works on chrome but it doesn't work on the mentioned browsers above. On scrollable page.

**Comment by ivansieder** [comment]
Hi @virtualbjorn, what exactly does not work? Do you have some code samples or a screen shot. Without any additional information it's hard to help right now.

**Comment by virtualbjorn** [comment]
@ivansieder you can reproduce this issue on the live demo as well
https://akryum.github.io/v-tooltip/#/ under **_Use with components to create a popover_**
the placement doesn't work

**Comment by ivansieder** [comment]
This works perfectly for me. Are you referring to the fact, that it gets moved from the bottom to the top if you are scrolling?

If you mean that, then that's by design from popper.js trying it's best to keep the popover in the user's viewport.

If you don't want that behaviour, try adding these options to your v-tooltip:
```javascript
popperOptions: {
  preventOverflow: {
    enabled: false
  }
}
```

**Comment by virtualbjorn** [comment]
placing that under preventOverflow doesn't seem to do anything.

**Comment by ivansieder** [comment]
Can you provide me a code sample on how you use the code and attach a screenshot on what it looks like for you?

**Comment by virtualbjorn** [comment]
I manage to find the right modifier.
```popperOptions: {`
      flip: {
             enabled: false
      }
}
``

**Comment by virtualbjorn** [comment]
Thanks for accommodating my issue. :)
