### ISSUE TITLE
span.trigger has inline style="display: inline-block"

### ISSUE THREAD

**Issue by rouxfeur** [Akryum/v-tooltip#160]
When using `v-popover`, there are two wrapper elements: `div.v-popover` and `span.trigger`.
```
<div class="v-popover">
    <span class="trigger" style="display: inline-block;">
        // Tooltip target
    </span>
</div>
```
`span.trigger` has a forced inline style `display: inline-block` which has frustrating whitespaces that are hard to get rid of. How can I remove it?

**Comment by gleb-cher** [comment]
+1

**Comment by lhermann** [comment]
I actually went ahead and forked it to add a `display` prop.

If you use `"v-tooltip": "git+https://github.com/lhermann/v-tooltip.git"` in your `package.json` you can do this:

``` html
<v-popover class="tooltip" display="block">
    ...
</v-popover>
```

or `display="inline"`.

**Comment by rootman** [comment]
For now, I did this:

```scss
.v-popover {
  display: flex;

  > .trigger {
    flex: 1 1 auto;
    max-width: 100%;
    outline: none;
  }
}
```

Depends on the case, but this covered all my cases so far. I wonder if it would be possible to have it renderless. The listeners could be passed by slot scope, but maybe this would hinder positioning of the popover.

**Comment by Akryum** [comment]
>  this would hinder positioning of the popover.

Most likely.

**Comment by lhermann** [comment]
@Akryum your v-popover plugin is really great, that's why I made a reproduction of the problem so this problem can be solved:

https://codepen.io/lhermann/pen/jobGNa?editors=1100

This pen shows the problem when wrapping a block-level element (like `div`) in `<v-popover>`.

As a current workaround, create this style:

```
.v-popover--block,
.v-popover--block > .trigger {
  display: block !important;
}
```

And add it to your v-popover element like so: `<v-popover class="v-popover--block">`

**Comment by Akryum** [comment]
I've removed the `inline-block` style in v3 alpha, we'll see how it goes.
