### ISSUE TITLE
v-tooltip on mobile

### ISSUE THREAD

**Issue by timeandtimeago** [Akryum/v-tooltip#168]
It would be great if v-tooltip has an "on click" event for mobile devices. 
Because of the fact that touch does not have a hover state - it makes v-tooltip unusable when you have to account for mobile devices. It would be great if there was also a click event on the trigger div.

**Comment by Akryum** [comment]
You can change the default trigger to click on mobile: https://github.com/Akryum/v-tooltip#global-options

**Comment by timeandtimeago** [comment]
Sweet. 
Thanks for the info!

**Comment by ingvijonasson** [comment]
I am wondering how this should be configures. In the global-options I see:
```
defaultTrigger: 'hover focus',
```
Should I configure this property to enable click for touch devices and how might can I accomplish that?

**Comment by yasoza** [comment]
for mobile: 
defaultTrigger: 'hover focus click'

**Comment by Kinzi** [comment]
This solved the issues on mobile for me:

```
Vue.use(VTooltip, {
  defaultTrigger: window.innerWidth > 768 ? 'hover focus click' : 'click'
})
```

**Comment by ali-so** [comment]
Is there any solution to set defaultTrigger: 'hover focus click' to just specific element in my .vue file?

**Comment by Anoesj** [comment]
I went another way, detecting whether the primary input mechanism can hover. This required me to use a computed for proper reactivity, because some devices can switch from `hover: none` to `hover: hover`, like a Microsoft Surface or a touch device with an external mouse/trackpad.

So instead of setting default values globally, I export this...
```ts
// Omit imports when using Nuxt with `floating-vue/nuxt`.
import { computed } from 'vue';
import { useMediaQuery } from '@vueuse/core';

const canHover = useMediaQuery('(hover: hover)');

export const tooltipOptionsDefaults = computed(() => ({
  showTriggers: canHover.value ? ['hover', 'focus', 'touch', 'click'] : ['click'],
  hideTriggers: canHover.value ? ['hover', 'focus', 'touch', 'click'] : ['click'],
  autoHide: !canHover.value,
  // ...other options
}));
```

...and use it like this:
```vue
<template>
  <div
    v-tooltip="{
      ...tooltipOptionsDefaults,
      content: 'Tooltip contents',
    }"
  >
    Lorem ipsum
  </div>
</template>

<script setup lang="ts">
  // Omit import when using Nuxt
  import { tooltipOptionsDefaults } from '...';
</script>
```

Still not perfect, because just because an external mouse is the primary input mechanism, the user can still use touch. In that particular case, this won't behave perfectly, but for now I'm okay with having that edge case.

**Comment by LeonardoRick** [comment]
Thank you so much, @Anoesj, for sharing your solution — it’s honestly the only reasonable implementation that offers great UX. It saved me a lot of time! 🥇
