### ISSUE TITLE
Accessibility: aria-describedby added too late?

### ISSUE THREAD

**Issue by dweldon** [Akryum/v-tooltip#191]
`v-tooltip` adds `aria-describedby` to the target element, which is fantastic. However, it doesn't become enabled until the first trigger has happened... which makes the description initially not available to screen readers (at least not on Vox+chrome).

* Is there some way to force add all instances of `aria-describedby` when the target element is rendered?
* Alternatively, is there some way to only add `aria-describedby` if `aria-label` does not exist?

**Comment by hrvojevu** [comment]
I was going to open this issue aswell. Can confirm that `axe` and `Siteimprove accessibility checker` chrome apps are flagging this as an issue also. It appears to me that the issue is that elements that have `v-tooltip` added to them have `aria-describedby` set to an `id` of a describing element (div) which is removed from the DOM tree after unhovering the element with tooltip.
