### ISSUE TITLE
Document how to use :container="false" to use the parent container automatically.

### ISSUE THREAD

**Issue by orrd** [Akryum/v-tooltip#368]
From reading the code, I learned that it's possible to have the Popover use the component's own parent as the "container" by setting the container to false with `:container="false"`.  I was glad to discover that because that was what I needed to make my code work.

Shouldn't that be in the documentation?

**Comment by Knogobert** [comment]
Thank you!!

**Comment by senatwj** [comment]
I was having an issue with y-axis placement being incorrect after scrolling down the page because of container elements being absolute positioned. Using this method to set a different container `:container="getContainer"` and 
`computed() {
...,
getContainer() { return document.querySelector('.container-selector') } }`
has appeared to fix this.

**Comment by Akryum** [comment]
Closed in #478
