### ISSUE TITLE
Tooltip don't work when app is on fullscreen

### ISSUE THREAD

**Issue by eveningforgery** [Akryum/v-tooltip#42]
Getting errors on hover when I put my app on fullscreen.

chrome 59 errors:
`Uncaught TypeError: Cannot read property 'offsetHeight' of null` from `popper.js`
`Uncaught TypeError: Cannot read property 'contains' of null` from `tooltip.js`

same issue on all browsers

**Comment by Akryum** [comment]
Do you have a repro?

**Comment by Akryum** [comment]
It's working in [the demo](https://akryum.github.io/v-tooltip/#/).

**Comment by gjactat** [comment]
Hello,
First of all, thanks for your great work !
I've set up a quick CodeSandBox that shows what happens when you bring a part of the page to fullscreen.
In this example, each blue button has a tooltip that works as expected. But when your bring that to fullscreen, the tooltips won't work anymore.
I guess this is related to the way poppers attach its dom elements to the body (which is probably not accessible from the fullscreen mode).
Maybe this could be fixed with an advances config ?

https://79ez9.csb.dev/
https://codesandbox.io/s/v-tooltip-fullscreen-79ez9 (fullscreen is not allowed inside CodeSandBowx editor. You have to test with the standalone url above).

Thanks for your attention

**Comment by igor-stupka** [comment]
Have same problem

**Comment by noook** [comment]
You need to set the container of the tooltips to an element within the element that is in full-size mode
