### ISSUE TITLE
This repository is dead

### ISSUE THREAD

**Issue by solidevolution** [Akryum/v-tooltip#588]

**Comment by kreig303** [comment]
hard to disgree.

alternatives??

**Comment by cjblomqvist** [comment]
We've created a non-specific (e.g. not providing tooltip/modal/xxx-specific code but like popper fully generic and up to the user to implement) popper wrapper which we'll try to get open sourced (needs some work to make it fully generic). It's using the latest version of popper, handles transitions, uses relevant portal/teleport instead of some custom implementation. Only supports Vue 2 atm.

If there's a lot of demand here I'll be motivated to push that effort.... ;) Otherwise I'll do it ASAP I find time for it...
